### PR TITLE
Bump version of non-semantic instruction set to 4

### PR DESCRIPTION
**Pull request by kpet**
We're already using instructions from version 3.

Signed-off-by: Kévin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Review by alan-baker — APPROVED** [review]

**Comment by alan-baker** [comment]
I think you might need to bump the deps for SPIRV-Tools and maybe SPIRV-Headers.

**Comment by kpet** [comment]
@alan-baker I've updated them both to the versions tracked by clvk that I've used for testing.

**Comment by alan-baker** [comment]
The amber tests are failing when trying to strip the non-semantic info instructions.

**Comment by alan-baker** [comment]
Finally got around to looking at this. Amber's deps were out of date so the validator was unhappy with the reflection version.

**Pull request merged**
