### PR TITLE
Update LLVM

### PR DESCRIPTION
**Pull request by jrprice**
* InstCombine replaces the code we generate for the rotate builtin
  with an llvm.fshl intrinsic, so handle that in ReplaceLLVMIntrinsicsPass

### CODE REVIEW

**Comment by jrprice** [comment]
The code in `replaceFshl` is almost the same as the code in `replaceRotate`, but slightly more general (`rotate` is essentially a specialized version of `llvm.fshl` where the first two arguments are the same).

We could avoid the code duplication by pre-empting `InstCombine` and just having `replaceRotate` generate a `llvm.fshl` directly, knowing that we run `ReplaceLLVMInstrincis` later in the flow. I can do this in a follow up PR if this sounds reasonable.

**Review by dnovillo — CHANGES_REQUESTED** [review]
Are there any existing tests that will exercise this transformation?

**Comment by jrprice** [comment]
> Are there any existing tests that will exercise this transformation?

The existing `rotate` tests cover it indirectly, but I've just added some additional tests that use it directly as well.

**Comment by dnovillo** [comment]
> > Are there any existing tests that will exercise this transformation?
> 
> The existing `rotate` tests cover it indirectly, but I've just added some additional tests that use it directly as well.

Thanks!  LGTM.

**Review by dnovillo — APPROVED** [review]

**Pull request merged**
