### PR TITLE
WIP: Read WorkgroupSize as whole vector from the spec constant value

### PR DESCRIPTION
**Pull request by dneto0**
Change the implementation of the get_local_size implementation to
avoid some driver bugs:
- One issue is trouble extracting individual elements.  It's seems to
  work better to read the entire vector at once.
- Another issue is that we have to extract directly from the spec
  composite value directly rather than from a variable initialized with
  that spec constant value.

### CODE REVIEW

**Comment by dneto0** [comment]
Tested on release and debug builds, and in hardware.

**Comment by dneto0** [comment]
LGTM

**Comment by dneto0** [comment]
No, not so fast.  Doesn't work in some scenarios.  My HW case wasn't right.

**Comment by sheredom** [comment]
I did see this bug on NVIDIA, but after filing it their latest drivers have fixed the issue fwiw.

**Comment by dneto0** [comment]
> I did see this bug on NVIDIA, but after filing it their latest drivers have fixed the issue fwiw.

Yes, I had the same experience.

**Comment by dneto0** [comment]
Rebased.
Tested in HW, and with Release and Debug builds.

I'd like to revisit this hack in the future.

**Comment by dneto0** [comment]
LGTM

**Pull request merged**
