### PR TITLE
Run clang-format on include/*.h and lib/*.cpp.

### PR DESCRIPTION
**Pull request by dnovillo**
I am working on a PR that needs to add minor changes to almost every file in lib/.  Since I have clang-format hooked to my buffer-save command, I got a massive diff because the files are not formatted automatically.

Can this be changed?

### CODE REVIEW

**Comment by kpet** [comment]
I completely support making this change (it would be great to have this checked by the bots so we don't go backwards after as well) but I would love it if you could defer this until after https://github.com/google/clspv/pull/336 goes in (I'm afraid I'd have to redo most of a big change which is otherwise ready-to-go). I'm totally fine with rebasing the other changes I have in flight.

**Comment by dnovillo** [comment]
Sure. I'll commit after your change. No worries

**Comment by dnovillo** [comment]
Let me know when your change is in.  I don't always monitor this repo.

**Comment by kpet** [comment]
Thanks, will do.

**Comment by kpet** [comment]
Well, Alan merged it in the time it took me to write the comment :).

**Comment by dnovillo** [comment]
> Well, Alan merged it in the time it took me to write the comment :).

Excellent.  Thanks.

**Comment by dnovillo** [comment]
Rebased after after @kpet changes.  @alan-baker PTAL.

**Comment by alan-baker** [comment]
I'll wait till #344 is finished to approve this.

**Comment by alan-baker** [comment]
@dnovillo can you rebase on trunk to get the format bot run on this?

**Pull request merged**
