### PR TITLE
build libclc libraries with clspv

### PR DESCRIPTION
**Pull request by rjodinchr**
Build libclc as part of the build system rather than relying on a checked-in bitcode file. This somewhat increases the duration of the build as clang, opt, etc are built as dependencies.

Ref #826

Based on #903

### CODE REVIEW

**Comment by rjodinchr** [comment]
I am working on the google infra as well.

**Comment by rjodinchr** [comment]
Updating llvm now generates vec8 when compiling `pow`. Not sure if it comes from an update in llvm or libclc.

**Comment by rjodinchr** [comment]
Depends on https://github.com/llvm/llvm-project/pull/87622

**Comment by rjodinchr** [comment]
Windows builds have been fixed by llvm/llvm-project@effb2f1917f11b58262d0e13aa085303b5896852

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
