### PR TITLE
Add support for image1d buffer

### PR DESCRIPTION
**Pull request by rjodinchr**
This patch is the complement of ongoing work on clvk side.

### CODE REVIEW

**Review by alan-baker — CHANGES_REQUESTED** [review]
I think this should not just map to a 1D image, but should instead map to an OpTypeImage with dimensionality of Buffer. That likely also means needing a different descriptor type so that the API can set it as either uniform texel buffer or storage texel buffer.

**Comment by rjodinchr** [comment]
I try to do it, but I end up with something that I don't understand yet.
A kernel using 1D image buffer generates a SPIRV code containing:
```
OpCapability SampledBuffer
%18 = OpTypeImage %int Buffer 0 0 0 1 Unknown
%37 = OpLoad %18 %21
%48 = OpImageFetch %v4int %37 %47 Lod|SignExtend %uint_0
```
and `spirv-val` returns an error:
```
error: line 95: Image Operand Lod requires 'Dim' parameter to be 1D, 2D, 3D or Cube
  %48 = OpImageFetch %v4int %37 %47 Lod|SignExtend %uint_0
```
While the [specification](https://www.khronos.org/registry/SPIR-V/specs/1.2/SPIRV.html#OpImageFetch) only mentions that:
```
Its Dim operand cannot be Cube, and its Sampled operand must be 1.
```
Could you help me on that point?

**Comment by alan-baker** [comment]
I think you may have to translate it as a storage image (i.e. Sampled=2).

**Comment by rjodinchr** [comment]
I am not sure how to translate it as a storage image.
I tried a few things, and always got:
```
error: line 94: Expected Image 'Sampled' parameter to be 1
  %47 = OpImageFetch %v4int %36 %46 Lod|SignExtend %uint_0
```

**Comment by alan-baker** [comment]
Sorry, for not explaining it further. If you generate a storage image, you'd then also generate OpImageRead instead of OpImageFetch.

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
