### PR TITLE
fix GetIdxsForTyFromOffset for struct of 1 element

### LINKED ISSUE #1120: assert when creating GEP in SimplifyPointerBitcastPass::runOnImplicitCasts
This is coming from #1109 @byzin

tests:
```
// type_test2.cl
struct Storage
{
  void set(const int value)
  {
    __generic int* ptr = reinterpret_cast<__generic int*>(&value_);
    for (size_t i = 0; i < 4; ++i)
      ptr[i] = value + static_cast<int>(i);
  }

  int sum() const
  {
    __generic const int* ptr = reinterpret_cast<__generic const int*>(&value_);
    int sum = 0;
    for (size_t i = 0; i < 4; ++i)
      sum += ptr[i];
    return sum;
  }

  int4 value_;
};

__kernel void test(__global int* outputs, __local Storage* storage)
{
  const size_t storage_id = get_local_id(0);
  __local Storage* s = &storage[storage_id];

  const size_t index = get_global_id(0);
  s->set(static_cast<int>(index));
  outputs[index] = s->sum();
}
```
```
// type_test3.cl
struct TestStruct
{
  void set(const int value)
  {
    __generic int* ptr = value_;
    for (size_t i = 0; i < 4; ++i)
      ptr[i] = value + static_cast<int>(i);
  }

  int sum() const
  {
    __generic const int* ptr = value_;
    int sum = 0;
    for (size_t i = 0; i < 4; ++i)
      sum += ptr[i];
    return sum;
  }

  int value_[4];
};

__kernel void test(__global TestStruct* inout)
{
  const int sum = inout[0].sum();
  inout[0].set(2 * sum);
}
```
compiled with:
```
clspv --cl-std=CLC++ --inline-entry-points <source> -o <dest>
```
produces:
```
clspv: clvk/external/clspv/third_party/llvm/llvm/include/llvm/IR/Instructions.h:933: Type *llvm::checkGEPType(Type *): Assertion `Ty && "Invalid GetElementPtrInst indices for type!"' failed.
```
backtrace:
```
* frame #0: 0x00007ffff78a9ccc libc.so.6`__pthread_kill_implementation(threadid=<unavailable>, signo=6, no_tid=<unavailable>) at pthread_kill.c:44:76
    frame #1: 0x00007ffff785aef2 libc.so.6`__GI_raise(sig=6) at raise.c:26:13
    frame #2: 0x00007ffff7845472 libc.so.6`__GI_abort at abort.c:79:7
    frame #3: 0x00007ffff7845395 libc.so.6`__assert_fail_base.cold at assert.c:92:3
    frame #4: 0x00007ffff7853df2 libc.so.6`__GI___assert_fail(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.c:101:3
    frame #5: 0x0000555558ae2cda clspv`llvm::checkGEPType(Ty=0x0000000000000000) at Instructions.h:933:3
    frame #6: 0x0000555558af534d clspv`llvm::GetElementPtrInst::getGEPReturnType(ElTy=0x000055555f0d9180, Ptr=0x000055555f1527f0, IdxList=ArrayRef<llvm::Value *> @ 0x00007fffffff94a8) at Instructions.h:1090:26
    frame #7: 0x0000555558af51e5 clspv`llvm::GetElementPtrInst::GetElementPtrInst(this=0x000055555f150d00, PointeeType=0x000055555f0d9180, Ptr=0x000055555f1527f0, IdxList=ArrayRef<llvm::Value *> @ 0x00007fffffff9530, Values=4, NameStr=0x00007fffffff9640, InsertBefore=0x000055555f158f10) at Instructions.h:1163:19
    frame #8: 0x0000555558af5181 clspv`llvm::GetElementPtrInst::Create(PointeeType=0x000055555f0d9180, Ptr=0x000055555f1527f0, IdxList=ArrayRef<llvm::Value *> @ 0x00007fffffff95b0, NameStr=0x00007fffffff9640, InsertBefore=0x000055555f158f10) at Instructions.h:974:25
    frame #9: 0x0000555558bc1376 clspv`clspv::SimplifyPointerBitcastPass::runOnImplicitCasts(this=0x000055555f0a21f8, M=0x000055555f06cc60) const at SimplifyPointerBitcastPass.cpp:556:20
    frame #10: 0x0000555558bbd811 clspv`clspv::SimplifyPointerBitcastPass::run(this=0x000055555f0a21f8, M=0x000055555f06cc60, (null)=0x00007fffffffad78) at SimplifyPointerBitcastPass.cpp:56:16
    frame #11: 0x0000555558a88db4 clspv`llvm::detail::PassModel<llvm::Module, clspv::SimplifyPointerBitcastPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(this=0x000055555f0a21f0, IR=0x000055555f06cc60, AM=0x00007fffffffad78) at PassManagerInternal.h:89:17
    frame #12: 0x000055555e777b77 clspv`llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(this=0x00007fffffff9bc8, IR=0x000055555f06cc60, AM=0x00007fffffffad78) at PassManager.h:517:40
    frame #13: 0x0000555558a5e629 clspv`(anonymous namespace)::RunPassPipeline(M=0x000055555f06cc60, binaryStream=0x00007fffffffaf58) at Compiler.cpp:741:9
    frame #14: 0x0000555558a5c6d8 clspv`(anonymous namespace)::CompileModule(input_filename=0x00007fffffffdc70, module=0x55555f06cc60, output_buffer=size=0, output_log=<parent failed to evaluate: parent is NULL>) at Compiler.cpp:1102:7
    frame #15: 0x0000555558a5a25f clspv`(anonymous namespace)::CompileProgram(input_filename=0x00007fffffffdc70, program="// RUN: clspv --cl-std=CLC++ --inline-entry-points %s -o %t.spv\n// RUN: spirv-val --target-env spv1.0 %t.spv\n\n\n// type_test2.cl\nstruct Storage\n{\n  void set(const int value)\n  {\n    __generic int* ptr = reinterpret_cast<__generic int*>(&value_);\n    for (size_t i = 0; i < 4; ++i)\n      ptr[i] = value + static_cast<int>(i);\n  }\n\n  int sum() const\n  {\n    __generic const int* ptr = reinterpret_cast<__generic const int*>(&value_);\n    int sum = 0;\n    for (size_t i = 0; i < 4; ++i)\n      sum += ptr[i];\n    return sum;\n  }\n\n  int4 value_;\n};\n\n__kernel void test2(__global int* outputs, __local Storage* storage)\n{\n  const size_t storage_id = get_local_id(0);\n  __local Storage* s = &storage[storage_id];\n\n  const size_t index = get_global_id(0);\n  s->set(static_cast<int>(index));\n  outputs[index] = s->sum();\n}\n\n/* // type_test3.cl */\n/* struct TestStruct2 */\n/* { */\n/*   void set(const int value) */\n/*   { */\n/*     __generic int* ptr = value_; */\n/*     for (size_t i = 0; i < 4; ++i) */\n/*       ptr[i] = value + stat"..., output_buffer=size=0, output_log=<parent failed to evaluate: parent is NULL>) at Compiler.cpp:1149:10
    frame #16: 0x0000555558a598b9 clspv`clspv::Compile(argc=6, argv=0x00007fffffffde48) at Compiler.cpp:1211:12
    frame #17: 0x0000555558a58d52 clspv`main(argc=6, argv=0x00007fffffffde48) at main.cpp:18:10
    frame #18: 0x00007ffff784618a libc.so.6`__libc_start_call_main(main=(clspv`main at main.cpp:17), argc=6, argv=0x00007fffffffde48) at libc_start_call_main.h:58:16
    frame #19: 0x00007ffff7846245 libc.so.6`__libc_start_main_impl(main=(clspv`main at main.cpp:17), argc=6, argv=0x00007fffffffde48, init=0x00007ffff7ffd020, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffde38) at libc-start.c:381:3
    frame #20: 0x0000555558a58c61 clspv`_start + 33
```

### PR DESCRIPTION
**Pull request by rjodinchr**
do not use dynamic index when detecting a struct of 1 element

Fix #1120

### CODE REVIEW

**Comment by rjodinchr** [comment]
I am not able to reproduce what is happening in `CI-ubuntu-clang-release`. It seems 1 test does not end, but I am not sure....

**Comment by rjodinchr** [comment]
It seems that `PointerCasts/invalid_local_cast.ll` is not completing. I need to look at it more to understand why.

**Comment by rjodinchr** [comment]
I have added a timeout in `PointerCasts/invalid_local_cast.ll`. The idea was to have more information about what was going wrong. But it "fixed" the test. Looks like the test alreay output the expected string, but for some reason it does not end (or does not return) when hitting the `llvm_unreachable` place just after (https://github.com/google/clspv/blob/main/lib/BitcastUtils.cpp#L1154).
Do you have an idea to help me debug it more? Or should we just keep it like that?

**Comment by alan-baker** [comment]
> I am not able to reproduce what is happening in `CI-ubuntu-clang-release`. It seems 1 test does not end, but I am not sure....

I retried the bot and the same thing happened. Do you know which test is not completing?

> I have added a timeout in `PointerCasts/invalid_local_cast.ll`. The idea was to have more information about what was going wrong. But it "fixed" the test. Looks like the test alreay output the expected string, but for some reason it does not end (or does not return) when hitting the `llvm_unreachable` place just after (https://github.com/google/clspv/blob/main/lib/BitcastUtils.cpp#L1154). Do you have an idea to help me debug it more? Or should we just keep it like that?

llvm_unreachable doesn't work as an assertion in release builds. So relying on that failure mode seems like the root of the problem. I'd be ok dropping the test and opening a separate issue if this is something we're actually running into.

There is a long-standing issue of being unable to surface internal compiler errors properly.

**Comment by rjodinchr** [comment]
Alright, then let's just remove this test, I don't think it is really needed.

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
